#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
#
# Author Trevor Steyn <trevor@webon.co.za

patton_cpu_default_values = (80, 90)

def inventory_patton_cpu(info):
   return [ ( None, "patton_cpu_default_values" ) ]


def check_patton_cpu(item, params, info):
   warn, crit = params
   cpu = int( info[0] [0] )
   perfdata = [ ( "cpu", cpu, warn, crit ) ]
   if (int(cpu)) < warn:
      return (0, "CPU Load '%d'%%" % cpu, perfdata )
   elif (int(cpu)) >= crit:
      return (2, "CPU Load '%d'%%" % cpu, perfdata )
   elif (int(cpu)) >= warn:
      return (1, "CPU Load '%d'%%" % cpu, perfdata )
   else:   
      return (3, "UNKNOWN - not valid value")

check_info["patton_cpu"] = {
    'check_function'        : check_patton_cpu,
    'inventory_function'    : inventory_patton_cpu,
    'service_description'   : 'CPU',
    'snmp_info'		    : ( '.1.3.6.1.4.1.1768.100.70.10.2.1', [ '2.1'] ),
    'snmp_scan_function'    :  lambda oid: oid(".1.3.6.1.4.1.1768.100.70.10.2.1.2.1") != None,
    'has_perfdata'	    : True
    }
