#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
#
# Author Trevor Steyn <trevor@webon.co.za

patton_active_calls_default_values = (60, 80)

def inventory_patton_active_calls(info):
   return [ ( None, "patton_active_calls_default_values" ) ]


def check_patton_active_calls(item, params, info):
   warn, crit = params
   calls = int( info[0] [0] )
   perfdata = [ ( "calls", calls, warn, crit ) ]
   if (int(calls)) < warn:
      return (0, "'%d' Active Calls" % calls, perfdata )
   elif (int(calls)) >= crit:
      return (2, "'%d' Active Calls" % calls, perfdata )
   elif (int(calls)) >= warn:
      return (1, "'%d' Active Calls" % calls, perfdata )
   else:   
      return (3, "UNKNOWN - not valid value")

check_info["patton_active_calls"] = {
    'check_function'        : check_patton_active_calls,
    'inventory_function'    : inventory_patton_active_calls,
    'service_description'   : 'Active Calls',
    'snmp_info'		    : ( '.1.3.6.1.4.1.1768.100.70.40.2.1', [ '3.2'] ),
    'snmp_scan_function'    :  lambda oid: oid(".1.3.6.1.4.1.1768.100.70.40.2.1.3.2") != None,
    'has_perfdata'	    : True
    }
