#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
#
# Author Trevor Steyn <trevor@webon.co.za>

def inventory_broadsoft_as_sip_invite_responses(info):
	if info:
		yield None, None

def check_broadsoft_as_sip_invite_responses(_no_item, _no_params, info):
	this_time = time.time()
	perfdata = []
	for line in info:
		perfdata.append(('rx_' + line[0],  get_rate('broadsoft_as_sip_invite_responses_rx_' + line[0], this_time, int(line[1]))))  		
		perfdata.append(('tx_' + line[0],  get_rate('broadsoft_as_sip_invite_responses_tx_' + line[0], this_time, int(line[2]))))
	return (0, 'OK - Total Transactions:' , perfdata )

# This check works on all SNMP hosts

check_info["broadsoft_as_sip_invite_responses"] = {
    'check_function':          check_broadsoft_as_sip_invite_responses,
    'inventory_function':      inventory_broadsoft_as_sip_invite_responses,
    'service_description':     'Broadsoft AS Invite Resonses',
    'snmp_info':               ('.1.3.6.1.4.1.6431.1.2.9.1.22.1', ['1', '2', '3']),
    'snmp_scan_function':      lambda oid: oid(".1.3.6.1.4.1.6431.1.2.9.1.22.1.1.100") not in [ None, "" ],
	'has_perfdata':            True,
}
