#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
#
# Author Trevor Steyn <trevor@webon.co.za>

def inventory_broadsoft_as_stats(info):
	if info:
		yield None, None

def check_broadsoft_as_stats(_no_item, _no_params, info):
	perfdata = [ ( "users",  info[0][0] ), ( "groups",  info[0][1] ), ( "enterprises",  info[0][2] ), 
				 ( "active_calls",  info[0][3] ), ( "calls_per_second",  info[0][4] ), 
                 ( "registration_per_minute",  info[0][5] ), ( "migrated_users",  info[0][6] ) ]
	return (0, 'OK - Users:' + info[0][0] + ', Groups:' + info[0][1]+ ', Enterprises:' + info[0][2] + ', Active Calls:' + info[0][3], perfdata )


check_info["broadsoft_as_stats"] = {
    'check_function':          check_broadsoft_as_stats,
    'inventory_function':      inventory_broadsoft_as_stats,
    'service_description':     'Broadsoft AS Statistics',
    'snmp_info':               ('.1.3.6.1.4.1.6431', ['1.2.16.1.2.0', '1.2.16.1.3.0', '1.2.16.1.4.0', '1.2.7.1.10.0', '1.2.7.1.12.0', '1.2.9.1.51.0', '1.2.18.1.1.0']),
    'snmp_scan_function':      lambda oid: oid(".1.3.6.1.4.1.6431.1.1.2.1.1.0") not in [ None, "" ],
	'has_perfdata':            True,
}
